# Generated by Django 5.0.6 on 2024-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.URLField(max_length=1024),
        ),
    ]
