# Generated by Django 5.0.6 on 2024-12-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_brand_color_size_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.URLField(max_length=1024)),
                ('image2', models.URLField(max_length=1024)),
                ('image3', models.URLField(max_length=1024)),
                ('image4', models.URLField(max_length=1024)),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('specifications', models.JSONField(default=dict)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('faq', models.JSONField(default=dict)),
                ('sku', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='mainApp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mainApp.category')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maincategory', to='mainApp.maincategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='mainApp.subcategory')),
            ],
        ),
    ]
