# Generated by Django 5.0.6 on 2024-12-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='maincategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='mainApp.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brands', to='mainApp.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='mainApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maincategory', to='mainApp.maincategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='mainApp.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='mainApp.category'),
        ),
    ]
