# Generated by Django 5.0.6 on 2024-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_product_discount_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.FloatField(blank=True, default=18, null=True),
        ),
    ]
