# Generated by Django 5.0.6 on 2024-12-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
