# Generated by Django 5.0.6 on 2024-12-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_basecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basecategory',
            new_name='Supercategory',
        ),
    ]
