# Generated by Django 5.0.6 on 2024-12-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_rename_basecategory_supercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='mainApp.supercategory'),
        ),
    ]
