# Generated by Django 5.0.6 on 2025-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='app_background',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
