# Generated by Django 5.0.6 on 2025-01-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_subcategory_app_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='app_background',
        ),
        migrations.AddField(
            model_name='category',
            name='app_background',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
