# Generated by Django 5.0.6 on 2025-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='background_image',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
