# Generated by Django 5.0.6 on 2025-01-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_supercategory_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.JSONField(default=dict)),
                ('image', models.URLField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addressType', models.CharField(default='', max_length=100)),
                ('alternatePhone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=10)),
                ('landmark', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=10)),
                ('pin', models.CharField(default='', max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.FloatField()),
                ('shippingPrice', models.FloatField()),
                ('finalPrice', models.FloatField()),
                ('transactionId', models.CharField(default='', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.address')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
            ],
        ),
    ]
